// <auto-generated />
using System;
using BlakeHunt_WebAPI_Final.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlakeHunt_WebAPI_Final.Migrations
{
    [DbContext(typeof(CustomersdbContext))]
    partial class CustomersdbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.11")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BlakeHunt_WebAPI_Final.Models.Products.Product", b =>
                {
                    b.Property<int>("ProductID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ProductID"));

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.Property<double>("Price")
                        .HasColumnType("float");

                    b.Property<string>("ProductDescription")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ProductName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("ProductID");

                    b.HasIndex("OrderId");

                    b.ToTable("Products");

                    b.HasData(
                        new
                        {
                            ProductID = 1,
                            Price = 10.0,
                            ProductDescription = "shirt",
                            ProductName = "shirt"
                        },
                        new
                        {
                            ProductID = 2,
                            Price = 20.0,
                            ProductDescription = "pants",
                            ProductName = "pair of pant"
                        },
                        new
                        {
                            ProductID = 3,
                            Price = 45.0,
                            ProductDescription = "for feet",
                            ProductName = "shoes"
                        });
                });

            modelBuilder.Entity("BlakeHunt_WebAPI_Final.Models.customers.Address", b =>
                {
                    b.Property<int>("AddressId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("AddressId"));

                    b.Property<string>("City")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("CustId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerCustId")
                        .HasColumnType("int");

                    b.Property<string>("State")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("StreetAdress")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("AddressId");

                    b.HasIndex("CustomerCustId");

                    b.ToTable("Address");

                    b.HasData(
                        new
                        {
                            AddressId = 1,
                            City = "Tenino",
                            Country = "United States",
                            CustId = 3,
                            State = "idk",
                            StreetAdress = "322 Gwen Street"
                        },
                        new
                        {
                            AddressId = 2,
                            City = "London",
                            Country = "United Kingdom",
                            CustId = 2,
                            StreetAdress = "556 Garb Rd"
                        },
                        new
                        {
                            AddressId = 3,
                            City = "Centralia",
                            Country = "United States",
                            CustId = 3,
                            State = "Washinton",
                            StreetAdress = "239 Silver Street"
                        });
                });

            modelBuilder.Entity("BlakeHunt_WebAPI_Final.Models.customers.Customer", b =>
                {
                    b.Property<int>("CustId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CustId"));

                    b.Property<string>("BirthDate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("OrderId")
                        .HasColumnType("int");

                    b.HasKey("CustId");

                    b.HasIndex("OrderId");

                    b.ToTable("Costomers");

                    b.HasData(
                        new
                        {
                            CustId = 1,
                            FirstName = "Gohn",
                            LastName = "Zmith"
                        },
                        new
                        {
                            CustId = 2,
                            FirstName = "Janice",
                            LastName = "1"
                        },
                        new
                        {
                            CustId = 3,
                            FirstName = "peith",
                            LastName = "lowercase"
                        });
                });

            modelBuilder.Entity("BlakeHunt_WebAPI_Final.Models.customers.Phone", b =>
                {
                    b.Property<int>("PhoneId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PhoneId"));

                    b.Property<int>("CustId")
                        .HasColumnType("int");

                    b.Property<int?>("CustomerCustId")
                        .HasColumnType("int");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("PhoneId");

                    b.HasIndex("CustomerCustId");

                    b.ToTable("Phone");

                    b.HasData(
                        new
                        {
                            PhoneId = 1,
                            CustId = 1,
                            PhoneNumber = "564-555-2535"
                        },
                        new
                        {
                            PhoneId = 2,
                            CustId = 2,
                            PhoneNumber = "020-555-2745"
                        },
                        new
                        {
                            PhoneId = 3,
                            CustId = 3,
                            PhoneNumber = "360-555-5764"
                        });
                });

            modelBuilder.Entity("BlakeHunt_WebAPI_Final.Models.orders.Order", b =>
                {
                    b.Property<int>("OrderId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("OrderId"));

                    b.Property<double>("Total")
                        .HasColumnType("float");

                    b.HasKey("OrderId");

                    b.ToTable("Orders");

                    b.HasData(
                        new
                        {
                            OrderId = 1,
                            Total = 500.0
                        },
                        new
                        {
                            OrderId = 2,
                            Total = 95.0
                        },
                        new
                        {
                            OrderId = 3,
                            Total = 44.450000000000003
                        });
                });

            modelBuilder.Entity("BlakeHunt_WebAPI_Final.Models.Products.Product", b =>
                {
                    b.HasOne("BlakeHunt_WebAPI_Final.Models.orders.Order", null)
                        .WithMany("ProductAddr")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("BlakeHunt_WebAPI_Final.Models.customers.Address", b =>
                {
                    b.HasOne("BlakeHunt_WebAPI_Final.Models.customers.Customer", null)
                        .WithMany("AddressAddr")
                        .HasForeignKey("CustomerCustId");
                });

            modelBuilder.Entity("BlakeHunt_WebAPI_Final.Models.customers.Customer", b =>
                {
                    b.HasOne("BlakeHunt_WebAPI_Final.Models.orders.Order", null)
                        .WithMany("CustAddr")
                        .HasForeignKey("OrderId");
                });

            modelBuilder.Entity("BlakeHunt_WebAPI_Final.Models.customers.Phone", b =>
                {
                    b.HasOne("BlakeHunt_WebAPI_Final.Models.customers.Customer", null)
                        .WithMany("PhoneAddr")
                        .HasForeignKey("CustomerCustId");
                });

            modelBuilder.Entity("BlakeHunt_WebAPI_Final.Models.customers.Customer", b =>
                {
                    b.Navigation("AddressAddr");

                    b.Navigation("PhoneAddr");
                });

            modelBuilder.Entity("BlakeHunt_WebAPI_Final.Models.orders.Order", b =>
                {
                    b.Navigation("CustAddr");

                    b.Navigation("ProductAddr");
                });
#pragma warning restore 612, 618
        }
    }
}
